### ISSUE TITLE
Circuit traces disconnect and scatter constantly.

### ISSUE THREAD

**Issue by Justnthenick** [fritzing/fritzing-app#3043] opened 2015-01-08 00:53 UTC
I save my circuit alot and I leave it open on my MacBook 2012 13 inch. I come back to it and the traces are all messed up. Some have skips in the traces and others arent connected, and just the other night, everything was done. This happens on every computer I own, all macs.
![nixie hv psu_etch_copper_top](https://cloud.githubusercontent.com/assets/10442754/5656204/c66e0930-968d-11e4-9392-f06d341549fd.jpg)
![screen shot 2015-01-06 at 12 30 08 pm](https://cloud.githubusercontent.com/assets/10442754/5656205/c67039a8-968d-11e4-9cce-897abaa9e420.png)

**Comment by KLiFF2606** [comment] 2015-11-27 16:54
I have the same issue on Ubuntu 14. When I reopen a file the traces are some how misinterpreted: the bend-points order is not read correctly. Here is an example of a trace with 2 bend-points:
- Before saving and closing the file the order is: A-B-C-D.
- After reopening the file: A-C-B-D.

I hope this helps to understand the bug.

**Comment by aknoerig** [comment] 2015-11-30 10:49
Duplicate of #3115. Thanks for the additional insight!

**Closed by aknoerig** 2015-11-30 10:49 UTC
