### ISSUE TITLE
autoplace

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#188] opened 2014-08-25 17:53 UTC
_From [brendan....@gmail.com](https://code.google.com/u/110718573451811856532/) on October 16, 2008 15:19:56_

The pcb layer should force or at least encourage users to only place parts
within actual board bounds.  Not critical for alpha.  Eventually would be
nice to even have a configurable parameter to keep folks from placing
things too close to the edge of a board.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=188_

**Comment by KjellMorgenstern** [comment] 2021-03-20 11:52
I tried placing 20 parts into the schematics view, and they were placed in the board in pcb view. So I think we can close this for pcb.

![image](https://user-images.githubusercontent.com/6494025/111868594-259d9880-897b-11eb-817a-8040cf0c0448.png)

**Closed by KjellMorgenstern** 2021-03-20 11:52 UTC
Labels: Autorouter, enhancement, imported

**Comment by failiz** [comment] 2021-03-20 12:11
Yes, I cannot reproduce it eaither. Maybe has been fixed or maybe they were reporting  #1490 which is still open.
