### ISSUE TITLE
The zip doesn`t give you the .exe to run the program

### ISSUE THREAD

**Issue by reinhard56** [fritzing/fritzing-app#3669] opened 2020-05-03 18:13 UTC
## Current Behaviour
Text
<please attach screenshot if possible>
**Build:**
<e.g. Version 0.9.3 (b5c895d32 2016-04-19) Cocoa [Qt 5.12.2]

**Operating System:**
<Windows 10>
The zip doesn`t give you the .exe to run the program
**Steps to reproduce:**
- Step 1 Download the zip
- Step 2

## Expected Behaviour
The expected thing is that you can get the .exe to be able to run it.

**Comment by KjellMorgenstern** [comment] 2020-05-04 06:22
Duplicate of #3668

**Closed by KjellMorgenstern** 2020-05-04 06:22 UTC
