### ISSUE TITLE
These wire is connected, but cannot show on PCB mode

### ISSUE THREAD

**Issue by TechD-Robin** [fritzing/fritzing-app#3153] opened 2015-11-03 13:33 UTC
as title, and issue like attachment.
I'm use Version 0.9.2 

![fritzing-bug](https://cloud.githubusercontent.com/assets/10447778/10909218/79ec947e-8272-11e5-8560-8fce75fba09f.png)

**Comment by landracer** [comment] 2015-11-04 03:24
This is a know bug. Don't save, close all open Fritzing windows, if using windoze reboot. Try again, do you still have the same issue?

**Comment by aknoerig** [comment] 2015-11-30 10:46
Duplicate of #3115. Thanks for the additional insight!

**Closed by aknoerig** 2015-11-30 10:46 UTC
