### ISSUE TITLE
Bug moving wires on PCB view

### ISSUE THREAD

**Issue by gepd** [fritzing/fritzing-app#3161] opened 2015-11-29 22:50 UTC
In this gif I show an weird bug when I try to move any wire from the PCB view, all they act like if they have an double "break point" (I  don't know how it's called) so everything gets a mess.

And when I try to undo the changes (ctrl + z) it never back to the initial position.

![bug1](https://cloud.githubusercontent.com/assets/7091609/11460802/cc8e9762-96d2-11e5-9900-6d80a9d95077.gif)

I think it's only a visualization problem because, when I close the program It didn't ask me for save changes, and when I re-open it, all is in order

I'm using Fritzing 0.9.2b 64bits
Windows 10 64bits

**Comment by aknoerig** [comment] 2015-11-30 10:46
Duplicate of #3115. Thanks for the additional insight!

**Closed by aknoerig** 2015-11-30 10:46 UTC
