### ISSUE TITLE
collect usage data

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#806] opened 2014-08-25 19:53 UTC
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 04, 2009 11:59:03_

It would be nice if fritzing collected some usage data and transmitted it to the 
website.  For example, the time the program starts up and shuts down.  It would be 
nice to correlate this with a particular instance of fritzing--Brendan suggests 
generating a GUID the first time, and stashing it somewhere to reuse later.  So we 
would send start time, shutdown time, and GUID.  

One major question is whether users will object.  One thought is the first time you 
run fritzing, you get a dialog telling you what's being collected, and asking 
permission.  This could be a setting in preferences, if the user wants to change 
his mind thereafter.

Another issue is about data collection.  For example, what if fritzing crashes, so 
you never get a shutdown.  What if the user puts the computer to sleep while 
fritzing is running, so the time between start and stop is skewed.  Finally, when 
do you send the data--at start up? at shut down?  both?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=806_

**Comment by failiz** [comment] 2020-10-18 09:05
This seems a duplicate of #1615

**Comment by KjellMorgenstern** [comment] 2020-10-18 12:34
Even before the GDPR was introduced, it should have been clear that Fritzing usage must be stored anonymized. Luckily, the ID mentioned here is not send. Beyond this it would be great to have crash reports and usage metrics (like slow startup times, and many many more), and in general be able to put our limited resource to those areas that need the most. But GDPR questions must be solved first, so closing this issue for now.

**Closed by KjellMorgenstern** 2020-10-18 12:34 UTC
Labels: Priority-Low, enhancement, imported
