### ISSUE TITLE
White note text

### ISSUE THREAD

**Issue by rr795** [fritzing/fritzing-app#3657] opened 2020-04-12 21:32 UTC
In version 0.94 on mac you cannot change the color of the notes, the text is white and you don't see almost

**Comment by rr795** [comment] 2020-04-12 21:33
<img width="503" alt="Captura de pantalla 2020-04-12 a las 23 33 24" src="https://user-images.githubusercontent.com/63563014/79080534-067f9b00-7d16-11ea-8492-e40b0dde350f.png">

**Comment by rr795** [comment] 2020-04-12 21:34
You cannot change the color of the text to black, or to another color

**Comment by theodore-dream** [comment] 2020-06-29 23:04
I am adding a comment here to note that I am facing this issue and I've researched this and there is no workaround for this issue. Notes are impossible to see.

fritzing-0.9.2b-20.fc32.x86_64
Fedora release 32 (Thirty Two)
kernel version 5.6.14-300.fc32.x86_64

Best,
Richard

**Comment by KjellMorgenstern** [comment] 2020-08-19 16:49
Duplicate of #3530

**Comment by domhardt** [comment] 2020-10-22 12:20
The problem still exists and there is no solution for it AND it includes Fritzing's "About" dialogue.

Fritzing Version 0.9.4 (CD-498-0-a1ffcea 2019-12-01) Cocoa [Qt 5.13.2]
MacOS 10.15.7 (19H2) Dark Theme

![VoltageDividerPullUpPullDown_bb](https://user-images.githubusercontent.com/1955290/96870610-71eab800-1471-11eb-9dcb-cbecd11b41d8.png)

![Bildschirmfoto 2020-10-22 um 14 19 28](https://user-images.githubusercontent.com/1955290/96870743-a199c000-1471-11eb-9d3f-748d69a21f3f.png)

**Comment by KjellMorgenstern** [comment] 2020-10-22 12:23
Yes, that why it is marked as solved (not closed) with the 0.9.5 milestone. It is fixed, but not yet released.

**Comment by domhardt** [comment] 2020-10-22 12:49
> Yes, that why it is marked as solved (not closed) with the 0.9.5 milestone. It is fixed, but not yet released.

Oh sry, I missed that. I'm waiting for the next release then. Thank you & keep on the good work!

**Comment by KjellMorgenstern** [comment] 2020-10-22 13:05
No problem, the "solved for milestone" concept is not used everywhere. I'll think about putting it in the README / contribution guidelines. And besides that, the 0.9.5 release really is overdue.

**Comment by failiz** [comment] 2021-03-12 22:01
Time to close all solved issues after the release of 0.9.6?

**Comment by KjellMorgenstern** [comment] 2021-03-12 22:50
Just retested, only partly solved. The "About" box still has the issue.

**Comment by domhardt** [comment] 2021-03-13 09:17
> Time to close all solved issues after the release of 0.9.6?

The release page still says that 0.9.4 is the latest stable release.

**Comment by failiz** [comment] 2021-03-13 11:54
@domhardt , 0.9.6 has been released on Feb 22. Where do you see that the latest version is 0.9.4?
https://blog.fritzing.org/2021/02/23/new-fritzing-release-096

**Comment by domhardt** [comment] 2021-03-13 11:56
> @domhardt , 0.9.6 has been released on Feb 22. Where do you see that the latest version is 0.9.4?
> https://blog.fritzing.org/2021/02/23/new-fritzing-release-096

Here:
[https://github.com/fritzing/fritzing-app/releases](https://github.com/fritzing/fritzing-app/releases)

**Comment by blurpy** [comment] 2021-03-23 18:09
I just tested 0.9.6 to see if the note text color was fixed, and it looks the same as 0.9.4, still white:

![fritzing-0 9 6-note](https://user-images.githubusercontent.com/186016/112196182-12086100-8c0b-11eb-86dd-9233431085bd.png)

openSUSE Tumbleweed with KDE.

**Comment by KjellMorgenstern** [comment] 2021-03-23 18:23
Is this from an official build? We only tested this on Ubuntu and MacOS, however there are very few platform specific styles, so the issue still occuring on 0.9.6 is a bit odd, no matter which system.

**Comment by blurpy** [comment] 2021-03-23 18:34
I downloaded the source from here: https://github.com/fritzing/fritzing-app/releases/tag/0.9.6
And followed the instructions from https://github.com/fritzing/fritzing-app/wiki/1.-Building-Fritzing to build it.
Then started it from the build directory.

Maybe it's related to me using dark mode on KDE?

**Comment by domhardt** [comment] 2021-03-23 18:35
While I'm willing to test there is still no recent stable version available on the releases page of this repo. :(

**Comment by blurpy** [comment] 2021-03-23 18:39
Stupid me, when I started the application from the build directory, I forgot `./` in the command, so I actually started 0.9.4. (>.<)
Sorry for the confusion. It shows like this now:

![fritzing-0 9 6-note2](https://user-images.githubusercontent.com/186016/112200310-66addb00-8c0f-11eb-9a1e-ed163dc4f2e1.png)

**Comment by KjellMorgenstern** [comment] 2021-03-23 18:46
@blurpy Thanks for clarification

**Comment by KjellMorgenstern** [comment] 2021-07-13 07:14
Various fixes have been deployed in 0.9.6 and 0.9.7 (rc3) , marking this as solved.
If there are still issues, or new issues, please open a separate ticket with exact version of Fritzing, Operating System and Color Scheme settings.

**Closed** 2021-07-25 08:59 UTC
Labels: solved
