### ISSUE TITLE
extra thick trace connection to thin connector

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2050] opened 2014-08-25 22:35 UTC
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 20, 2012 08:33:24_

the connection looks pinched.

**Attachment:** [shot.png](http://code.google.com/p/fritzing/issues/detail?id=2050)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2050_

**Comment by failiz** [comment] 2021-12-28 15:07
From the old forum:
"Bobble-wire-bug
Views: 488

Latest post time: 2012-08-24 09:54:39 UTC

Author: 4041

Body:

Hi,

When I reopen a saved PCB-design with thick wires (70 or above) they becomes bobble-shaped. Really strange. Here is a screenshot: https://www.dropbox.com/s/yxeqvv7vsgr2wri/fritzingbug.png

Rickard.

Time: 2012-08-22 21:31:37 UTC

Edited at:

Author: 8

Body:

Hi Rickard,

This is not exactly a bug. Traces have rounded ends where the radius is width / 2. So the little bubbles are actually the two rounded ends and no middle, due to the short trace distances on your sketch. At 70mils, the "bubble" has almost the same radius as the connector, so that makes it seem even more like a bubble. For a wire with some extent in the middle, have a look at the horizontal trace at the left edge of the sketch from the dropbox image. 

There is an update bug--the wire is not reseating after the width is changed. If you happen to move a connected part, the trace will reseat (and that is effectively what happens when you reload the file).

I think we do have to reconsider the rounded ends. For a workaround, if you are worried about the electrical connection, you could draw longer traces (where you have a line of traces, draw a single trace between the furthest ends), or you could use a copper logo item or a pad part.

Cheers,

- j

Time: 2012-08-22 22:26:37 UTC

Edited at:

Author: 4041

Body:

The rounded ends look great at smaller widths, why not make it an option that you can turn on?

It also seems like they are not applied if I make a new connection between two points. That's why I thought this was a bug, because when I deleted one of these bubbles and made a new connection it was straight.

Rickard"
This is the image from the Dropbox link:
![image](https://user-images.githubusercontent.com/5708642/147579810-d486bffb-80ed-4b83-ab6c-5747be27573d.png)

**Comment by failiz** [comment] 2021-12-28 15:14
I think that this is a duplicate of #3316, which has been fixed by #3379.

**Comment by KjellMorgenstern** [comment] 2024-06-26 06:33
This is resolved. I also tried reloading the sketch, it shows the same as the initial rendering.

![image](https://github.com/fritzing/fritzing-app/assets/6494025/b4f33157-6fdd-448f-859c-da662e3f2db7)

Remove the ".log", because github will not let us upload Fritzing files:
[bubble.fzz.log](https://github.com/user-attachments/files/15983459/bubble.fzz.log)

**Closed** 2024-06-26 06:35 UTC
Labels: enhancement, imported
