### ISSUE TITLE
pinheader double row smd 1.27mm spacing: pads overlap

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2776] opened 2014-08-26 11:56 UTC
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 12, 2013 01:52:42_

need a way to modify pad size

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2778_

**Comment by failiz** [comment] 2021-03-16 22:56
Duplicate of  #2758

**Closed** 2021-03-17 08:34 UTC
Labels: bug, imported
