### ISSUE TITLE
It's really difficult to just move components in PCB view

### ISSUE THREAD

**Issue by Kazade** [fritzing/fritzing-app#3197] opened 2016-03-01 16:44 UTC
If I just want to select a component in PCB view, I can't just click on it, I have to hover the mouse around until I hit just the right place and then click - and sometimes that's not possible because of other components getting in the way!

It would be great if there was a modifier key which basically meant "always select component/wire" rather than creating a new trace.

**Comment by Kazade** [comment] 2016-03-01 16:59
See also #2663

**Comment by failiz** [comment] 2021-03-25 08:23
Duplicate of  #2663. Close

**Comment by KjellMorgenstern** [comment] 2021-03-26 17:44
Closing as duplicate.

**Closed by KjellMorgenstern** 2021-03-26 17:44 UTC
