### ISSUE TITLE
0.9.10 in "read only mode"

### ISSUE THREAD

**Issue by dvarrel** [fritzing/fritzing-app#4028] opened 2023-05-17 05:37 UTC
## unable to modify
interface is ok, but i can't modify : unable to move or pick components, like "read only mode"
works fine with the old version 0.9.6 installed with apt

<e.g. Version 0.9.10 (bCD-2134-0-40d23c29 2022-07-01) 64 [Qt 5.15.2]
<ubuntu 23.04>

![Capture d’écran du 2023-05-17 07-36-43](https://github.com/fritzing/fritzing-app/assets/6559309/38bac16f-f292-4e17-883c-a04d5cd910fb)

**Comment by KjellMorgenstern** [comment] 2023-05-17 05:39
Duplicate of #4025

**Closed as completed by KjellMorgenstern** 2023-05-17 05:39 UTC
