### ISSUE TITLE
grid color under custom background color

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2792] opened 2014-08-26 11:56 UTC
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 03, 2013 01:34:29_

use some kind of opposite color generator

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2794_

**Comment by Sigma-One** [comment] 2017-09-11 14:02
This would definitely be useful.

**Comment by failiz** [comment] 2021-03-22 23:19
Remove imported label

**Comment by failiz** [comment] 2021-03-27 10:05
Duplicate of #3750

**Closed** 2021-03-27 20:03 UTC
Labels: Priority-High, Usability, enhancement
