### ISSUE TITLE
Expand / Contract the selection using SHIFT select

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#145] opened 2014-08-25 17:50 UTC
_From [dirk.van...@gmail.com](https://code.google.com/u/102845219688896911239/) on October 07, 2008 11:21:20_

What steps will reproduce the problem? 1. You want to select multiple parts on the canvas but not everything in a region.

The shift modifier to add stuff to the selection or remove stuff from there should work by either (shift) clicking or (shift) drawing a selection box.

This might have implications for other uses of the shift modifier (e.g. to create bend points on a 
wire)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=145_

**Comment by failiz** [comment] 2020-10-28 22:15
The COMMAND / CTRL works for selecting both ways (clicking or drawing a selection box.). The only issue is that it cannot be configured to use the shift key instead of the  COMMAND / CTRL.

**Comment by failiz** [comment] 2021-03-27 09:34
Duplicate of #1971

**Closed** 2021-03-27 19:59 UTC
Labels: Priority-Low, Usability, enhancement, imported
