### ISSUE TITLE
Position of dropdown on Mac OS X Yosemite

### ISSUE THREAD

**Issue by ronaldlokers** [fritzing/fritzing-app#3054] opened 2015-02-12 16:58 UTC
When I click on a item that opens a dropdown I get some unexpected behaviour. The dropdown will be opened on another position then where I clicked.

This problem prevents me to go fullscreen because some popups will else open outside of the window.

Please let me know if you need any extra information to be able to reproduce this problem.

![untitled_sketch_fzz_-_fritzing_-__pcb_view_](https://cloud.githubusercontent.com/assets/303084/6172315/4e491142-b2e0-11e4-9d0e-b0a97679419e.png)

**Comment by ronaldlokers** [comment] 2015-02-16 16:15
I discovered that I don't have this problem when I use just 1 display, it only happens when I have 2 displays. So I think this is the same problem as in #3036

But the white text color in the popup is also there when using just 1 color, so that is another bug.

**Comment by failiz** [comment] 2021-03-12 19:08
This is a duplicate of #3036
Not sure about the white colour, but I think that it has been addressed.

**Comment by KjellMorgenstern** [comment] 2022-11-16 22:55
The colors are fixed already.
I tried to reproduce the dropdown location issue in a dual screen setup, on macOS Ventura, with vertical and horizontal screen arrangement, but could not reproduce the issue.

**Closed by KjellMorgenstern** 2022-11-16 22:55 UTC
