### ISSUE TITLE
Raspberry v2 Part introduced in 0.9.2b is buggy

### ISSUE THREAD

**Issue by thommi2k** [fritzing/fritzing-app#3076] opened 2015-04-15 23:56 UTC
* all 3v3 and GND pins in the GPIO header seem to be connected internally.
* unless GIPO is some new nomenclature I'm not aware of, all GPIOs are misspelled.

**Comment by el-j** [comment] 2015-04-16 09:32
thanks for the report.
- yes: gnd, 3v3 and 5v pins are connected internally, because they have the same signal. is that not correct? does it make any difference which gnd, 3v3 or 5v is used?
- the misspelling goes back to the first raspi version. thx and fixed

**Comment by thommi2k** [comment] 2015-04-16 10:58
Sorry, I did not phrase this well. What I mean is that all 3v3 pins are internally connected TO all gnd pins, surely that can not be right?

**Comment by el-j** [comment] 2015-04-16 11:32
hej again,
i'm sorry but i cannot confirm this bug. tested in all 3 view. the internal connections seems to be right from my point of view. 
![rasp2_no-bus-bug](https://cloud.githubusercontent.com/assets/2795534/7179891/b2fed4ae-e43c-11e4-9cc7-8aebe08843d2.png)

**Comment by thommi2k** [comment] 2015-04-16 12:05
That does look right, yes. I will check when i come home.

**Comment by thommi2k** [comment] 2015-04-16 21:06
Well, there is some kind of bug, but it actually is not the Raspberry part...
Not sure how this can happen, I had a wire which shorted the 3v3 to GND as soon as one end was connected to the Raspberry 3v3, even if the other end wasn't connected to anything.

Screenshots:

![wire-1](https://cloud.githubusercontent.com/assets/9590840/7191345/17fb9c02-e48d-11e4-9164-0a55454b3506.png)
(raspberry without the crazy wire: ok)

![wire-2](https://cloud.githubusercontent.com/assets/9590840/7191356/2a60a18a-e48d-11e4-9938-eddf956d353c.png)
(raspberry with the wire just connected to 3v3: shorted to gnd ???)

**Comment by el-j** [comment] 2015-04-17 09:14
so, this is a bug with your sketch. as you see your green wire is connected to something, otherwise the end of the wire have to be "red" for "not connected". the green wire has green ending point. i do not know how that happen, but it's not a bug in the raspbi part.
so i close this issue

**Closed by el-j** 2015-04-17 09:14 UTC

**Comment by thommi2k** [comment] 2015-04-17 10:42
I'd say it's a bug in the wire part if it is possible to create such a wire, although I can't tell you how this happened.
