### ISSUE TITLE
Simply doesn't work: Components selection leads to a disabled mouse icon.

### ISSUE THREAD

**Issue by bhabegger** [fritzing/fritzing-app#4025] opened 2023-05-06 16:47 UTC
I just downloaded Fritzing after paying the 8€ fee to be able to use the simulator... But this versions doesn't work where the opensource version does... See the attached video.

[Screencast from 2023-05-06 18-41-14.webm](https://user-images.githubusercontent.com/1582356/236636750-125e8b72-c65e-4cdd-8fcf-0b7514ff119d.webm)

**Comment by KjellMorgenstern** [comment] 2023-05-06 17:11
Could you add the linux version, window manager version and 3rd party fritzing build version?

Edit: Looks like Kudu , so probably Ubuntu 22.10 or 23.04. I'll try to reproduce it on 23.04.

**Comment by KjellMorgenstern** [comment] 2023-05-07 12:35
Seems like this is not a Fritzing bug, but the linux distribution, and affects a plethora of applications.

https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/2013235

https://gitlab.gnome.org/GNOME/mutter/-/issues/2715

https://forum.qt.io/topic/144831/recent-upgrade-to-ubuntu-23-04-breaks-qt-designer?lang=de

**Comment by dvarrel** [comment] 2023-05-17 05:40
yes , same issue with ubuntu 23.04 ( works fine before with ubuntu 22.04 )

**Comment by KjellMorgenstern** [comment] 2023-05-17 06:54
We experimented, but it seems the solution would then break Fritzing for all other users (eg. ubuntu 22.04). 
One workaround if you don't want to downgrade is using Xfce.

**Comment by dvarrel** [comment] 2023-05-17 06:55
how do you break Fritzing for all other users ?

**Comment by KjellMorgenstern** [comment] 2023-05-17 06:55
adding native wayland support

**Comment by dvarrel** [comment] 2023-05-17 06:56
seems 23.04 use wayland no ?

**Comment by dvarrel** [comment] 2023-05-17 07:46
fritzing is a appimage,, so i can't choose the qt library wayland

**Comment by KjellMorgenstern** [comment] 2023-05-17 09:01
I didn't suggest wayland, but Xfce.
To avoid misunderstandings: Drag and Drop in Ubuntu 23.04 works when using Xfce.  
This issue is not really related to wayland, but to a bug in Mutter, that has been fixed, but the fix will probably take some time to make it into Ubuntu.

**Comment by bhabegger** [comment] 2023-05-28 08:08
And how is using xfce done ?

**Comment by KjellMorgenstern** [comment] 2023-05-28 08:15
Install xfce with your packet manager. Then choose Xfce in the login screen:

![image](https://github.com/fritzing/fritzing-app/assets/6494025/c6c61d3c-3b4f-4521-acb1-8498a207bead)


![image](https://github.com/fritzing/fritzing-app/assets/6494025/0d495277-6b65-48f4-8e19-c9387947e515)

**Comment by KjellMorgenstern** [comment] 2023-05-28 09:51
Another workaround is described here, compiling mutter from source. It was confirmed to work on all Qt applications, so should also work for Fritzing. Don't try this unless you know what you are doing.
Note that you have to repeat the steps for each update to libmutter until the fix is included by ubuntu. 

https://github.com/OpenShot/openshot-qt/issues/5221#issuecomment-1546539610

**Comment by dvarrel** [comment] 2023-05-30 04:28
It works, thanks you very much !!!

Le 28 mai 2023 09:52:01 UTC, Kjell ***@***.***> a écrit :

**Comment by KjellMorgenstern** [comment] 2023-07-18 13:19
The issue was fixed in mutter 44.2
https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/2013235

Which was release with "lunar-updates" for 23.04:
https://packages.ubuntu.com/search?keywords=mutter&searchon=names&suite=lunar-updates&section=all

**Closed as completed** 2023-07-18 13:19 UTC
Labels: solved
