### ISSUE TITLE
redundant connection in bbview can break existing connection in schematic view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2137] opened 2014-08-25 22:39 UTC
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 25, 2012 00:59:23_

described here http://fritzing.org/forum/thread/1047

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2137_

**Comment by failiz** [comment] 2021-03-14 12:13
Not enough information

**Comment by KjellMorgenstern** [comment] 2021-12-09 13:01
Including information from old forum (2012-07-24 07:43:52 **UTC**)

To reproduce:

1. Start a new file.
2. Place a resistor on the breadboard so its legs are at holes A1 and A5. Then stretch the right leg to A10.
3. Place a second resistor on the breadboard so its legs are B1 to B5. Don't stretch its legs yet.
4. Switch to schematic view. Connect up pin 0 to pin 0 on the two resistors. Connect up pin 1 to pin 1.
5. Switch back to breadboard view. A virtual wire has appeared between pin 1 of R1 and pin 1 of R2.
6. Stretch the right leg of R2 to hole B10. The virtual wire dissapears. OK so far...
7. Switch back to schemaitc view. Drag R2 around. You should see that although pin 0 of R1 and R2 remain connected, the pin 1s have become disconnected, leaving a "dangling" wire and a new virtual wire between the two.

**Comment by KjellMorgenstern** [comment] 2021-12-09 13:04
Looks like a duplicate of #3740

**Closed by KjellMorgenstern** 2021-12-09 13:04 UTC
Labels: bug, imported, Priority-High
