### ISSUE TITLE
Schematic view - snap "magnets" aren't strong enough

### ISSUE THREAD

**Issue by daxliniere** [fritzing/fritzing-app#3602] opened 2020-02-01 14:18 UTC
## Current Behaviour
Could a dev please adjust the snap threshold in the Schematic view? I find that when I connect a component to a wire or create a new point on a wire, even when the wire was perfectly aligned to the grid, that point is always created/moved SLIGHTLY off the grid and needs to be moved on. Even moving it on isn't easy every time.
It seems like the virtual 'magnets' or 'detents' aren't strong enough to pull the points to the grid intersections.

(Separately, thank you for your amazing work. I'm glad to be a financial contributor and really do appreciate this project. :) )

**Build:**
Version 0.9.4 
(CD-498-0-a1ffcea 2019-12-01) 64 [Qt 5.12.3]

**Operating System:**
Windows 10

**Comment by KjellMorgenstern** [comment] 2020-02-03 17:43
Which component did you use? Maybe there is an issue with parts that define a very small endpoint. Connecting wires to a resistor in schematics view is a pretty standard task, and I don't find it difficult at all (but I am biased :-) )

**Comment by daxliniere** [comment] 2020-02-03 22:44
Hey Kjell! Thanks for taking the time to answer my reports.
I'm referring to the wires in Schematic view. Please see the attached screencap.
![Fritzing_SnapStrength](https://user-images.githubusercontent.com/8109020/73697523-ae556880-46d6-11ea-969a-844713be6dd5.gif)

**Comment by failiz** [comment] 2021-11-02 21:33
Duplicate of #3738

**Closed** 2022-06-01 15:35 UTC
Labels: bug, solved
