### ISSUE TITLE
The part editor is not loading silkscreens

### ISSUE THREAD

**Issue by matissev** [fritzing/fritzing-app#3193] opened 2016-02-23 11:58 UTC
Hello,

I'm having trouble with the part editor in Fritzing 0.9.2 as it is not loading the silkscreen of my part, although the copper layers are fine. It seems that it can recognize the svg path but can't display it black.
However, the schematics works. Didn't try the breadboard view though.
I tried to import the svg file of a standard IC that has a working silkscreen with no success.
I also tried to make a new .fzpz package, to convert units to inches, and to remove all the custom parts in the custom parts folder in order to avoid conflicts, but nothing works.

Here it is as a .svg file :
[pcb.svg.zip](https://github.com/fritzing/fritzing-app/files/142433/pcb.svg.zip)

and here is the .fzpz file :
[A4988 Stepper Motor Driver Carrier.fzpz.zip](https://github.com/fritzing/fritzing-app/files/144520/A4988.Stepper.Motor.Driver.Carrier.fzpz.zip)

Thanks in advance.

**Comment by KjellMorgenstern** [comment] 2019-11-20 11:13
This might already be fixed on 0.9.5 develop branch.

**Comment by DrItanium** [comment] 2020-01-04 02:34
Hmmmm, when I try to load the file I get an error with the message:

There is already a part with id '0223_0eb44bbb4c4f50c21567b8c79110a3c3_5' loaded into Fritzing.

Tested with 0.9.5 development branch

**Comment by KjellMorgenstern** [comment] 2020-01-04 08:01
The issue is for sure outdated,
the root cause might or might not be fixed,
the provided A4988 has conflicts with another part which is already obsolete.
A nice A4988 part is available ( Pololu A1)

Therefore I will close the issue.

**Closed by KjellMorgenstern** 2020-01-04 08:01 UTC
Labels: Parts-Editor, easy start
