### ISSUE TITLE
Schematics to PCS engine

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2972] opened 2014-08-26 14:39 UTC
_From [mkrs...@gmail.com](https://code.google.com/u/116903339167717453589/) on June 27, 2014 11:10:56_

What steps will reproduce the problem? 1. simple create a more complicated schematics
2. try to generate the PCB

I did find the software very good designed, easy to learn,
spent 3 hours making a schema with about 30 electronic parts,
when i clicked PCB and autogenerate,
well,It blew me OFF!!!

the software CANNOT place the stuff on PCB, and I really tried
to fix it,no way.

IMPROVE the placement of parts, not only the wiring!!!!!!!!!!!!
!!!!!!!!!!!!!!!11

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2974_

**Comment by failiz** [comment] 2020-10-21 09:21
Duplicate of #188?

**Comment by failiz** [comment] 2021-03-19 21:59
Ping

**Comment by KjellMorgenstern** [comment] 2021-03-20 11:55
Kind of a duplicate of #188 , although the OP seemed to expect and AI to place the parts. Closing as either fixed, or out of scope. If someone wants to try such an AI, let me know :-)

**Closed by KjellMorgenstern** 2021-03-20 11:55 UTC
Labels: bug, imported
