### ISSUE TITLE
resizing a perfboard scrambles the layout of whatever parts were connected

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1711] opened 2014-08-25 21:34 UTC
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 30, 2011 18:55:54_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1711_

**Comment by failiz** [comment] 2021-03-18 19:54
I think that #3414 is a duplicate of this one. But it is better documented than this one. So, close this one?

**Comment by KjellMorgenstern** [comment] 2021-03-18 20:07
Closing in favor of #3414

**Closed by KjellMorgenstern** 2021-03-18 20:07 UTC
Labels: Priority-High, bug, imported
