### ISSUE TITLE
bendpoint falling off the grid when a new trace is connected to it

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1869] opened 2014-08-25 22:27 UTC
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 02, 2012 07:23:53_

when you create a "biegepunkt" that has snapped to grid, then connect a new 
wire, the "biegepunkt" goes to the point where you released the mouse button, so  you have to push the point to the grid again. It would be better if the new wire  would snap to the "biegepunkt" like it snaps to all other parts.

**Attachment:** [pic_02.png](http://code.google.com/p/fritzing/issues/detail?id=1869)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1869_

**Comment by kittentronic** [comment] 2021-04-01 11:29
Shouldn't this count as a Bug, not just an Enhancement?

**Comment by KjellMorgenstern** [comment] 2021-04-01 12:02
Still reproducable with 0.9.6

**Comment by failiz** [comment] 2021-11-03 23:11
Duplicate of #3738 and #3602

**Closed** 2022-06-01 15:37 UTC
Labels: bug, solved
