### ISSUE TITLE
Properties.xml to fritzing-parts

### ISSUE THREAD

**Issue by el-j** [fritzing/fritzing-app#3303] opened 2017-01-16 17:03 UTC
for all the parts with different value properties we need to move the properties.xml from 
the fritzing source to the fritzing-parts-repository. now we need to build a new release,
if new properties and value-rows are added or modified, because the xml is compiled into
fritzing. 

it should be sit in the friting-parts-repositories so it can be updated without the fritzing main releases.

**Comment by failiz** [comment] 2021-03-16 22:49
Is this a duplicate of #2486?

**Comment by KjellMorgenstern** [comment] 2021-03-17 09:19
It seems part of #2486

**Closed by KjellMorgenstern** 2021-03-17 09:19 UTC
Labels: Parts
