### ISSUE TITLE
Unable to modify generic IC on MAC OS

### ISSUE THREAD

**Issue by MikeTinsley** [fritzing/fritzing-app#3862] opened 2021-08-09 12:54 UTC
## Current Behaviour
Attempting to change number of pins on generic IC from 8 to 16 (or anything else) results in this error:

 Parse error (2) at line 1, column 1:
unexpected end of file
/Users/michaeltinsley/.config/Fritzing/partfactory/eda1b1e76ca3627c596ba0a2b34794ab/core/generic_ic_dip__300mil.fzp
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/88664684/128709161-96b8f066-73aa-4b08-85da-08b4aef9fe3d.png">

**Build:**
Version 0.9.7
**Operating System:**
macOS Big Sur 11.4

**Steps to reproduce:**
select generic IC and place on schematic
attempt to change number of pins

## Expected Behaviour
IC is modified accordingly

**Comment by KjellMorgenstern** [comment] 2021-08-09 13:18
Duplicate of #3859

**Closed by KjellMorgenstern** 2021-08-09 13:18 UTC

**Comment by MikeTinsley** [comment] 2021-08-09 15:46
Have now downloaded 0.9.8 and it works - problem solved
