### ISSUE TITLE
IEC schematic symbols

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1333] opened 2014-08-25 21:16 UTC
_From [fda...@online.nl](https://code.google.com/u/107932673981941701484/) on February 05, 2011 05:03:28_

To: André Knörig:

Find attached the IEC (european standards) alike schematic for a number of components of the resistor family. You'll find the current core symbols of version 2010.09.30.pc and some new.
All symbols are drawn with a 2,4px stroke. All pins are 0,1inch x 2,2 px and all terminals are 2,2px dots.

For the current core symols I used the same name for easy replacement. I propose however the naming always to start with the family name, like:
- resistor_basic, resistor_trimmer, resistor_varistor, etc

Some comments and questions:
- the current schematic symbol for the trimmer is not correct (find the correct one in resistor_trimmer)
- is the current photocel a resistance (LDR) or a photo-diode?
- is the current thermistor an NTC or PTC? (I attached both)

Please let me know if you can approve the used dimensioning, symbols and naming. If you like I can send you more schematic IEC alike symbols in the same way.

A strange thing I found is that a core componenent has a gridsnap at the terminals end and the same component as a user component has a grid snap in the center of the terminal?

Frits, username FritzWare

**Attachment:** [basic_fsr.svg basic_poti.svg ldr.svg resistor_magnetic.svg resistor.svg resistor_strain.svg resistor_trimmer.svg resistor_ntc.svg resistor_ptc.svg resistor_varistor_neg.svg thermistor.svg](http://code.google.com/p/fritzing/issues/detail?id=1333)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1333_

**Comment by KjellMorgenstern** [comment] 2019-11-04 17:28
Unfortunately the files have been deleted with google code. 

Please attach files to this issue. It would be best if IEC schematics symbols would match the symbols used in fritzing in style and size (line width etc).

**Comment by failiz** [comment] 2023-06-08 07:39
This issue is a duplicate of #2567. Should we close this issue in favor of #2567?

**Comment by KjellMorgenstern** [comment] 2024-12-04 20:53
Closing in favor of #2567

**Closed by KjellMorgenstern** 2024-12-04 20:53 UTC
Labels: enhancement, grab me / help wanted, easy start
