### ISSUE TITLE
validated text entry is a pain in the ass

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2260] opened 2014-08-25 22:45 UTC
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on October 13, 2012 06:52:20_

The validator does not allow intermediate values. Maybe best to check validation only at focus-out time. Unfortunately, focus-out event management is also a big pain...

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2260_

**Comment by failiz** [comment] 2021-03-12 16:17
This is fixed with my pull request, which is more merged in the simulator branch.
In addition, it's a duplicate of #1262

**Comment by KjellMorgenstern** [comment] 2021-03-12 17:51
Closed in favor of #1262

**Closed** 2021-03-12 17:50 UTC
Labels: Priority-High, bug, imported
