### ISSUE TITLE
resizing of stage that occurs with parts moving does not undo with undo

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#480] opened 2014-08-25 18:08 UTC
_From [jenn...@gmail.com](https://code.google.com/u/118211363250187816324/) on January 16, 2009 07:33:13_

What steps will reproduce the problem? 1. Move part to the auto-scrolling area so that it moves and widens stage
2. Click control-z to undo
3. Part goes back to the original location, but stage is still "widened"

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=480_

**Comment by failiz** [comment] 2021-03-22 21:26
Still valid. remove imported label, add UI

**Comment by KjellMorgenstern** [comment] 2024-08-02 11:17
The view menu has options to resize, and there is the <kbd>Ctrl</kbd>+<kbd>0</kbd> for "Fit in Window" (as well as a "physical size" view). The scrollbars indicate the position. 

The issue is 15 years old. Fritzing *and* UI/UX expectations have changed a lot since then.

Usually zoom or scrolling is not an "edit" that can be undone? There might be better ways to avoid mismatched stage areas, make the user aware of it, or give even better control over it.

But these should be handled in a new issue. Closing this one.

**Closed by KjellMorgenstern** 2024-08-02 11:17 UTC
Labels: bug, UI
