### ISSUE TITLE
Label position not retained during SMD swap

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1417] opened 2014-08-25 21:21 UTC
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on March 30, 2011 17:02:24_

What steps will reproduce the problem? 1. Place an LED on the breadboard
2. Change the position of its label
3. Swap it to SMD

The label jumps back to the default position - actually also in the other views. That's not a showstopper, but can be quite annoying.
And it doesn't happen when swapping within THT parts.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1417_

**Comment by failiz** [comment] 2021-01-31 13:26
Still an issue in 0.9.4. Currently, it also happens when swapping within THT parts.

**Comment by failiz** [comment] 2021-12-13 09:02
Duplicate of #3735?

**Comment by KjellMorgenstern** [comment] 2023-11-23 09:26
The fix made it into one of the release some time ago, just confirmed that it works with 1.0.1,  but probably also before.

**Closed by KjellMorgenstern** 2023-11-23 09:26 UTC
Labels: bug, Parts, solved
