### ISSUE TITLE
Crashes on MacOS whilst loading components

### ISSUE THREAD

**Issue by SWills73** [fritzing/fritzing-app#4089] opened 2023-12-04 18:11 UTC
## Current Behaviour
Fritzing 1.01 crashes soon after loading  components.

**Build:**
Version 1.0.1  (and version 1.0.0)
(rcCD-1653-0-8d480a18 2023-09-04) Cocoa [Qt 6.4.3]

**Operating System:**
MacOS Sonoma Version 14.1.2
Apple MacBook Pro 2019 with Intel chip

**Steps to reproduce:**
- Load Fritzing
- Click on one of the parts lists and during loading components it crashes and exits
- Also crashes when trying to load a circuit example

NOTE: Versions 0.9.10 seems to be stable with none of these crashing issues.

**Comment by failiz** [comment] 2023-12-11 08:17
duplicate of #4088

**Comment by KjellMorgenstern** [comment] 2023-12-11 13:08
I was able to try this on a fresh Ventura 13.6.1 on an Intel Xeon iMac Pro.

Fritzing 1.0.1 , downloaded from our own website. Loading several examples, as well as adding some parts to a fresh sketch (resistors, diodes, several of the ESP8266 / ESP32 ).
Also made some traces in the PCB, added copper fill etc, and uploaded it to the Aisler Fab.

No crashes occured.

Tried again with Sonoma 14.1.2 and a Fritzing dev build ( 1.0.2 ).  Also no crashes.

**Comment by KjellMorgenstern** [comment] 2023-12-11 13:12
There are few reports on this crash, it seems to work for the vast majority of users.
It doesn't look like this is related to macOS on Intel CPUs, at least it works here.

What else could #4088 and #4089 have in common?

**Comment by failiz** [comment] 2023-12-11 19:21
Probably not related, but the fact that the crash is produced after dragging parts reminded  me #4025

**Comment by KjellMorgenstern** [comment] 2023-12-11 20:27
Could be. My test system for sure has different graphic and input drivers.

**Comment by KjellMorgenstern** [comment] 2024-01-08 18:03
We have released Fritzing 1.0.2, which might have fixed the problem. We can´t yet reproduce it, so I can not verify. In any case, please continue on issue #4088 .

**Closed as completed by KjellMorgenstern** 2024-01-08 18:03 UTC
