### ISSUE TITLE
big copy/paste issues

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1916] opened 2014-08-25 22:29 UTC
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 31, 2012 14:18:10_

see file from issue #1911 .  

"I want to take the chance to explain why I copied and why I moved the breadboard around.

You may take this as an input for improvements

I have the task to create several times the same layout as I have several channels (currently 4 but may extend to 8 or more)

As I do not wanted to invent the wheel again and again.

But I needed still to be able to edit e.g. the channels go to different Arduino inputs.

ð  I copied the breadboard to generate the same circuit several times  => That’s why find the copying bug

But this approach has generated to much work for me as the copied layout appears with ratsnest (the copied version)

As I did not want to perform the routing again I started to copy the layout instead.

This maintains the layout and you can still work in the layout for adaptions without routing everything again.

But doing the copy in the layout has doubled the breadboard view and the schematic exactly in the same position.

To avoid this I moved in advance the breadboard and the schematics to the left down corner before copying layout  => That’s why I find the moving bug.

Doing this moving in advance the copy of the breadboard and schematics shows up in a different location then original when doing the layout copy (BTW the layout needs also be moved in advance to avoid showing up in the same position)

It seems that the copies show up always centered.

My idea of improvement would be

If you copy layout let show the copy of breadboard and schematics at a different place than the original in any case (even if not moved out of center in advance)

Or allow to drag the copy away (currently not possible in schematics view)

And provide the option to add a breadboard to the copy (when you have copied from the layout)

This would allow to develop further in this view easily.

My current workaround to avoid the problem with moving the breadboard was to select all parts in the original version and to activate lock.

If the copy shows up at the same location you can drag away the copy of the breadboard circuit.

Please note the copy in the breadboard view is without breadboard just the parts with ratsnest (if you do the copy of the layout and admire what happens in the two other views)

If you have no breadboard under laid =>  no issue with moving the circuit/components in this view found.

This workaround does not work for schematics view still drag in advance away of the original needed.

But moving the schematics is not causing any corruption (as far as I see)."

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1916_

**Comment by KjellMorgenstern** [comment] 2022-01-28 11:29
Closing this as duplicate of #1352

**Closed by KjellMorgenstern** 2022-01-28 11:29 UTC
Labels: bug, imported
