### ISSUE TITLE
Mouse hover menu unreadable due to color scheme

### ISSUE THREAD

**Issue by giovi321** [fritzing/fritzing-app#4118] opened 2024-02-13 08:11 UTC
## Current Behaviour
When hovering with the mouse over the pin of a part, a menu opens but it appears unreadable as the text color is too similar to the background color.
![immagine](https://github.com/fritzing/fritzing-app/assets/6443515/f0726e34-8029-491c-bdae-f80a03f00bc2)

**Build:**
Version 1.0.2 
(bCD-1901-0-dbdbe34c 2023-12-20) 64 [Qt 6.5.3]

**Operating System:**
Windows 10

**Steps to reproduce:**
- Insert a new part (any part with pins)
- hover with the mouse on a pin to read the label

## Expected Behaviour
Better contrast on the text against the background

**Comment by KjellMorgenstern** [comment] 2024-02-13 09:51
Duplicate of #4109

**Closed as completed by KjellMorgenstern** 2024-02-13 09:51 UTC
