### ISSUE TITLE
Headers don't reflect settings

### ISSUE THREAD

**Issue by holgerlembke** [fritzing/fritzing-app#3085] opened 2015-05-15 05:33 UTC
- create new schematic
- add generic female Header
- set 8 Pins

Change view to pcb view
- set form to long pad
- set pin distance to 2 mm

--> settings are accepted, but layout does not change

**Comment by marc-gist** [comment] 2015-10-30 13:13
This is also true when changing the "row" from single, to double.  It still displays as a single row on the Breadboard, but the PCB shows the double row.

**Comment by chrisyokum** [comment] 2015-12-18 01:15
This seems to be an issue regardless of whether you try to place a "Generic Female Header" or "Generic Shrouded Header" - both will render nicely on the PCB but are unusable on the Breadboard/Perfboard.

Is there some way I can fix this myself?

**Comment by chrisyokum** [comment] 2015-12-18 01:33
Nevermind.. "Mystery part" to the rescue!

**Comment by chrisyokum** [comment] 2015-12-18 01:39
Whenever this is fixed, it would be nice to use the pin numbering in zig-zag form. I notice that the "male shrouded" has the numbers counter-clockwise/anticlockwise from 1. It should be zig-zag across (odd on one side, even on the other) for these expansion connectors.. https://en.wikipedia.org/wiki/Insulation-displacement_connector

**Comment by failiz** [comment] 2021-03-13 19:38
Confirmed in 0.9.6
Add bug and PCBView labels

**Comment by failiz** [comment] 2021-03-13 19:42
Related to #2199 #2923 and  #2758

**Comment by KjellMorgenstern** [comment] 2021-12-09 13:39
Closing in favor of #2625

**Closed** 2021-12-09 13:41 UTC
Labels: bug
