### ISSUE TITLE
pin spacing selection for long pad form of headers

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2625] opened 2014-08-26 11:49 UTC
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on June 14, 2013 20:57:51_

What steps will reproduce the problem? 1. Drag a header onto the PCB
2. Select long pad from "form"
3. choose any pin spacing, none of them have any effect, the pin spacing is always 2.54mm no matter what you choose

See image attached showing pin spacing 1.27mm selected, but 2.54mm drawn

Long pads are _really_ important for 1.27mm pitch headers, there just isn't a realistically sufficient surface area with a standard ring pad.

**Attachment:** [longpad.png](http://code.google.com/p/fritzing/issues/detail?id=2627)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2627_

**Comment by failiz** [comment] 2021-04-24 19:04
Duplicate of #3085

**Comment by failiz** [comment] 2021-06-11 21:33
Ping

**Comment by failiz** [comment] 2021-11-21 12:22
Any reason to keep this open?

**Comment by KjellMorgenstern** [comment] 2021-12-09 13:38
Issue #3085 has some unrelated comments, lets track the issue with oblong pads here.

**Closed as completed** 2023-07-18 12:13 UTC
Labels: bug, solved
