### ISSUE TITLE
Cursor Glitch

### ISSUE THREAD

**Issue by Dario-64** [fritzing/fritzing-app#4043] opened 2023-07-18 12:26 UTC
Mouse pointer glitches when pointing a part in the Breadboard view.

![2023-07-18 14_08_32-Untitled Sketch fzz_ - Fritzing -  Vista Breadboard](https://github.com/fritzing/fritzing-app/assets/113928175/eb4a99d6-0992-46d6-bb47-8f3c04bfa38a)

**Build:**
Version 1.0.0 (rcCD-4157-0-6b14cfe9 2023-06-02) 64 [Qt 6.4.3]

**Operating System:**
Microsoft Windows 10 Version 22H2 (build 19045.3208)

**Comment by failiz** [comment] 2023-07-18 12:54
Duplicate of #4037

**Closed as completed** 2023-07-18 12:55 UTC

**Comment by KjellMorgenstern** [comment] 2023-07-18 13:00
@DarioGAMER64 Can you post which graphic card or driver you use?

**Comment by Dario-64** [comment] 2023-07-18 20:09
My PC is Dell Latitude 7280, and my graphics card is Intel(R) HD Graphics 520.
