### ISSUE TITLE
Unable to update on mac OS Sierra 10.12.2 just after installing

### ISSUE THREAD

**Issue by dymbox** [fritzing/fritzing-app#3293] opened 2016-12-30 06:37 UTC
After installing on Mac OS X Sierra 10.12.2 & checking for updates the following happens:

![screen shot 2016-12-30 at 09 27 47](https://cloud.githubusercontent.com/assets/6935268/21560612/e3503248-ce72-11e6-8290-839f2d1430f1.png)

Then it downloads something and shows the following dialog

![screen shot 2016-12-30 at 09 28 24](https://cloud.githubusercontent.com/assets/6935268/21560617/fed259ec-ce72-11e6-8f9f-e31eb98ef773.png)

Then it closes itself, and on reopen says this

![screen shot 2016-12-30 at 09 28 42](https://cloud.githubusercontent.com/assets/6935268/21560630/1729ced0-ce73-11e6-85b1-ee219de6bb89.png)

Then I'm trying to update it again thru Help -> Check for updates, and it shows me this

![screen shot 2016-12-30 at 09 29 09](https://cloud.githubusercontent.com/assets/6935268/21560642/362d8600-ce73-11e6-9ac4-47d469c5ef6a.png)

Finally, if I follow its advice and gonna try to rebuild the parts database, it says this

![screen shot 2016-12-30 at 09 29 32](https://cloud.githubusercontent.com/assets/6935268/21560653/51869612-ce73-11e6-804f-54a539842405.png)

No manual update attempts performed from my side, just dragged it from .dmg to /Applications and started as brand new app.

**Comment by mw9** [comment] 2016-12-31 20:11
I have the same problem with OSX El Capitan 10.11.6.

Got this message box when initially updating:

![fritzing problem](https://cloud.githubusercontent.com/assets/319101/21579081/2f33302a-cf95-11e6-9d66-8a4d21a55867.png)

Thereafter I experience much the same as the OP.

**Comment by VeitSanner** [comment] 2017-01-13 09:22
Same for me. Let's **up-vote** this issue.

**Comment by hunter-nl** [comment] 2017-02-13 14:25
I have also exactly the same problem on MacSierra 10.12.3. When can we expect a fix for this issue?

**Comment by wez** [comment] 2017-02-19 03:54
I'm seeing the same thing.  https://github.com/fritzing/fritzing-app/issues/3308 is a duplicate of this issue and some folks have reported that chmod'ing the $TMPDIR fixes it; it does not have any effect for me (the permissions on TMPDIR are correct, and honestly, suggesting making it 777 is very dangerous advice).

I've tried running Fritzing under dtruss but it doesn't show any failed syscalls relating to opening files or making directories, so I'm stumped as to what exactly it is failing on. :-(  Best thing to do as a workaround is just not update the parts library AFAICT.

**Comment by gt500sc** [comment] 2017-02-19 19:31
This worked for me:
http://superuser.com/questions/1133065/unable-to-write-to-tmp-osx-unable-to-correct-permissions-operation-not-permitt

**Comment by VeitSanner** [comment] 2017-03-07 08:35
This issue has been tagged with 'priority-critical' but work does not seem to have been started. The same applies to the duplicate #3308.

As @wez mentions modifying the permissions for $TMPDIR is not the best idea. Especially Apple could just reset permissions to default permissions with the next macOS update.

When can we expect a fix for the issue?

CC: @aknoerig

**Comment by aknoerig** [comment] 2017-12-18 09:49
Please try the fix that was just merged (see #3308). Hope this works for all of you!

**Closed** 2017-12-18 09:51 UTC
Labels: bug, OpSys-OSX, Parts, Priority-Critical
