### ISSUE TITLE
Initial  PCB view after schematic design has many components on top of each other

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2664] opened 2014-08-26 11:50 UTC
_From [SharmanJF](https://code.google.com/u/SharmanJF/) on July 15, 2013 01:15:12_

What steps will reproduce the problem? 1.Do a complex design, e.g. lots of small components like decoupling capacitors
2. See the resulting birdsnest in PCB view.  Many components are on top of each other.  Ratsnest hotspots where this is happening. 3. Attach your sketch file and/or custom part files to the bug report. What is the expected output? Spread out components so they can be quickly re-organised. 
What do you see instead? Very crowded hotspots.

What version of Fritzing are you using? 0.8b On what operating system? Windows 7 Professional 64-bit. Please provide any additional information below.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2666_

**Comment by failiz** [comment] 2021-03-27 11:07
duplicate of #188, which we could not reproduce. Close

**Closed** 2021-03-27 20:04 UTC
Labels: enhancement, imported
