### ISSUE TITLE
Wrong resolution?

### ISSUE THREAD

**Issue by hmrodrigues** [fritzing/fritzing-app#3259] opened 2016-07-13 22:32 UTC
When I try to run the app or is too big (on screen 1920x1080) or too small (on screen 1366x768). Either way, I can't resize the window.

I tried using the package manager install and the linux64 from the download page.

**EDIT**: I'm able to open with the _right ui_ if I turn off the 1080p display, but not the other way around.
After opening the app, I can re-enable the screen, resize to the _big one_ and open new windows without problems

**System**
- Arch Linux
- Gnome 3.20.2

**1366x768**
![1366x768](https://cloud.githubusercontent.com/assets/8062666/16822003/9a4ec13c-4951-11e6-876b-8328496a9f2a.png)

**1920x1080**
![1920x1080](https://cloud.githubusercontent.com/assets/8062666/16822002/9a4adb26-4951-11e6-9a31-f2868d4fd0f1.png)

**Disable and re-enable 1080p display**
![screenshot from 2016-07-13 23-40-36](https://cloud.githubusercontent.com/assets/8062666/16822293/533683b4-4953-11e6-9daf-9078cc3c5215.png)

**Comment by alan-martinovic** [comment] 2016-07-28 13:20
Am also having this issue on Ubuntu 16.04.

Not sure what you mean by `I turn off the 1080p display`...
Physically powering it on and off?

**Comment by alan-martinovic** [comment] 2016-07-28 13:37
Here is a workaround that worked on Ubuntu:

```QT_AUTO_SCREEN_SCALE_FACTOR=0.75 ./Fritzing```

[Reference](https://wiki.archlinux.org/index.php/HiDPI#Qt_5)

**Comment by jogi-k** [comment] 2016-08-05 10:32
I am having the same issue on Ubuntu 14.04 on a Full-HD-Display.
The mentioned workaround from alan-martinovic worked also here.

Jogi

**Comment by nodice73** [comment] 2016-08-10 23:11
I think this is the same issue as #3221. See if you agree.

**Comment by jws121295** [comment] 2016-12-26 02:32
It appears this is still an issue. I don't believe #3221 is related. As mentioned above, setting QT_AUTO_SCREEN_SCALE_FACETOR does the trick. I had to set it to something other than 1. It will work with anything in the form "0.x", however entering different values doesn't seem to have any effect.

**Comment by TeaPackCZ** [comment] 2016-12-31 12:17
I'm afraid, that it has smt to do with this:
From https://wiki.archlinux.org/index.php/HiDPI#Qt_5 :
"Note if you manually set the screen factor, it's important to set QT_AUTO_SCREEN_SCALE_FACTOR=0 otherwise some applications which explicitly force high DPI enabling get scaled twice"

**Comment by pjockey** [comment] 2017-11-22 20:22
Is there a place to put the QT_AUTO_SCREEN_SCALE_FACTOR=0 in order to start the program from the GUI?

**Comment by pylover** [comment] 2018-05-28 19:03
```bash
QT_SCALE_FACTOR=3 QT_AUTO_SCREEN_SCALE_FACTOR=0 Fritzing
```

Fixed my problem on Surface Pro 4(4K screen):
![screenshot from 2018-05-28 23-32-19](https://user-images.githubusercontent.com/1302253/40626696-73be8964-62cf-11e8-87c7-d2d9742c904c.png)

**Comment by failiz** [comment] 2021-11-08 08:36
Duplicate of #3221
No reports since 2018, fixed?

**Comment by KjellMorgenstern** [comment] 2023-05-25 12:16
DPI settings in Fritzing, Qt and most of the OS / Window Managers have changed a lot. Usually reports do not contain enough information to reproduce similar issues. I observed the issues when using multiple screens that have different DPIs, especially when one of the screens was switched on or off. Often, DPI or zoom settings from the system play an important role.

To mitigate the issue, it would make sense to review Fritzing with the latest recommendations from Qt:
https://doc.qt.io/qt-6/highdpi.html
In general, we will try to let UI elements size more flexible.

But I don't think there is a single bug or missing improvement that would allow for a 'fix'.

**Closed by KjellMorgenstern** 2023-05-25 12:16 UTC
