### ISSUE TITLE
random silkscreen on the edge of boards.

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2918] opened 2014-08-26 12:02 UTC
_From [petegrim...@gmail.com](https://code.google.com/u/113828317411017930470/) on February 09, 2014 22:45:34_

What steps will reproduce the problem? 1.4 different projects have been ruined by this bug and i have lost money 2. 3. Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please provide any additional information below.

**Attachment:** [extended gerber files.zip i (1).png i.png](http://code.google.com/p/fritzing/issues/detail?id=2920)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2920_

**Comment by KjellMorgenstern** [comment] 2019-12-12 10:53
Sorry, I have to close this issue, as none of the attachments have been rescued to github. 
We don't know if the issue is fixed or not, but some improvements have been done since the. To both, gerber export and parts format parsing stability.

**Closed by KjellMorgenstern** 2019-12-12 10:53 UTC
Labels: ImportExport, bug, imported
