### ISSUE TITLE
many buggy parts uploaded to issue 875

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2565] opened 2014-08-26 11:46 UTC
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 10, 2013 01:56:33_

Many of these parts are buggy, which means they cause crashes or buggy behavior in Fritzing, or we have to deal with them at fab time. It would be nice to clear out the buggy ones, as well as the ones that are now represented in the core.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2567_

**Comment by failiz** [comment] 2020-10-18 08:55
The issue #875 has been closed. The buggy parts have not been specified and the bugs have not been described. The wish for a check of the parts seems to be a duplicate of  #111. Close?

**Closed** 2020-10-18 11:42 UTC
Labels: Parts, Priority-High, Web, bug, imported
