### ISSUE TITLE
Autrouter ignores single layer setting

### ISSUE THREAD

**Issue by chrisspen** [fritzing/fritzing-app#3211] opened 2016-05-16 02:57 UTC
I'm trying to design a single-layered board, and even though I've set the PCB's layer to "one layer (single-sided)", when I run the auto-router, it creates a second layer with a ton of vias, which I then have to delete. How do I stop this from happening?

If it's not possible to routing my circuit with a single layer, that's fine, but I'd prefer to get an error message saying "unroutable" instead of it added a bunch of extra parts that I can't use.

**Comment by YaseenTwati** [comment] 2016-06-02 17:36
can you upload your .fzz file ?

**Comment by YaseenTwati** [comment] 2016-07-08 12:39
it works normally here ... maybe a version, os, fzz file or a bit more info ?

**Comment by failiz** [comment] 2021-03-12 21:08
I could not duplicate it in 0.9.6 (Windows) and not enough information

**Comment by KjellMorgenstern** [comment] 2021-03-12 21:50
The autorouter has the ability to add wires to bridge connections when routing is to complex or impossible. I could imagine something similar happens with single sided boards.

**Comment by failiz** [comment] 2021-03-12 22:03
It could be, but it uses jumper for that, not traces on top.
By the way, this looks like a duplicate of #3211

**Comment by failiz** [comment] 2021-03-12 22:05
Sorry, duplicate of #3347

**Comment by KjellMorgenstern** [comment] 2021-03-12 22:38
Closing in favor of #3347

**Closed by KjellMorgenstern** 2021-03-12 22:38 UTC
Labels: Autorouter, PCB View, bug
