### ISSUE TITLE
Core Parts Missing in 0.9.3b

### ISSUE THREAD

**Issue by granitepenguin** [fritzing/fritzing-app#3310] opened 2017-02-03 20:14 UTC
OS: macOS 10.11.6
Fritzing version: 0.9.3b

Just updated from 0.9.2 and now when Fritzing starts, I get the following error when loading Core Parts:
![screen shot 2017-02-03 at 14 13 25](https://cloud.githubusercontent.com/assets/913430/22606861/013c91d4-ea1b-11e6-9ade-839ecc5fe3f4.png)

Tried deleting my fritzing directory and starting again, but problem still persists.

**Comment by VeitSanner** [comment] 2017-03-07 08:42
@granitepenguin, do you experience the same issues as detailed in #3293?

**Comment by granitepenguin** [comment] 2017-03-07 14:45
basically, yes.  I get the same "Parts > Regenerate parts database..." suggestion but I can't do that because it's greyed out in the menu, so I never get to the "Unable to open temporary file" dialog.

**Comment by granitepenguin** [comment] 2017-03-07 14:50
If I open a new project, I get the Regenerate Parts Database dialog, and it does do the same thing, so this looks like it is a duplicate of #3293

**Comment by VeitSanner** [comment] 2017-03-09 12:47
@granitepenguin, thanks for the confirmation.

@aknoerig, is there a chance to close this issue and use #3293 for als further discussions?

**Comment by granitepenguin** [comment] 2017-03-09 14:19
FWIW, I would be fine with that.

**Comment by aknoerig** [comment] 2017-12-18 09:50
Closed as duplicate of the above mentioned.

**Closed by aknoerig** 2017-12-18 09:50 UTC
