### ISSUE TITLE
Removing bend point on a part sometimes causes leg to disconnect from part

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2950] opened 2014-08-26 12:03 UTC
_From [Per...@gmail.com](https://code.google.com/u/101092636704265404242/) on April 27, 2014 14:29:59_

What steps will reproduce the problem? 1. On a prototype board, add a part (such as a resistor).
2. Drag one of its legs longer and add a bend point.
3. Delete the bend point and the leg detaches itself; ends up floating near part. disappears when you delete part. Attach your sketch file and/or custom part files to the bug report. I don't currently have an example to show. What is the expected output? What do you see instead? The bend point should disappear, leaving the leg connected to the part. Instead the leg disconnects and floats separated near the part. Only solution I've found is to delete the part and add a new version. What version of Fritzing are you using? On what operating system? Version 0.8.7 on a Mac Laptop using Mac OSX 10.6.8 Please provide any additional information below.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2952_

**Comment by failiz** [comment] 2021-03-21 21:00
I managed to reproduce it in 0.9.6 at the second attempt. After that, I could not trigger the error after 20/30 attempts.
Remove imported label. Add BreadboardView

**Comment by KjellMorgenstern** [comment] 2024-12-12 08:56
Could not reproduce this with Fritzing 1.0.4, closing

**Closed by KjellMorgenstern** 2024-12-12 08:56 UTC
Labels: bug, Priority-High
