### ISSUE TITLE
Crash when right-clicking Note

### ISSUE THREAD

**Issue by daniellm19** [fritzing/fritzing-app#3884] opened 2021-09-25 17:24 UTC
## Current Behaviour
Right clicking the text section of the "Note" core part in the "Tools" section when you have dragged it on to the breadboard causes the application to crash. I can't really screenshot it since the application crashes immediately.

Version 0.9.9 (bCD-348-0-f0af53a9 2021-09-22) [Qt 5.15. (the rest doesn't show up)
![image](https://user-images.githubusercontent.com/89205836/134780449-c1c6e19e-cc71-400c-86a5-482768b8d869.png)

**Operating System:**
Windows 10

**Steps to reproduce:**
- Step 1: Drag the "Note" core part in the "Tools" section to the breadboard.
- Step 2: Right-click the text section of the "Note" core part in the breadboard.

## Expected Behaviour
To get possible options? I was just trying to right-click and it just crashed so I can't know the expected behaviour.

**Comment by daniellm19** [comment] 2021-09-25 17:26
I just realized that someone had already written this issue, but maybe that just speeds up the fixing process.

**Comment by KjellMorgenstern** [comment] 2021-09-28 16:47
Closing as duplicate of #3880

**Closed by KjellMorgenstern** 2021-09-28 16:47 UTC
