### ISSUE TITLE
pcb view - dragging a selection group doesn't move bendpoints

### ISSUE THREAD

**Issue by JC3** [fritzing/fritzing-app#3906] opened 2021-11-25 00:28 UTC
## Current Behaviour

selecting an area that includes bend points and then attempting to move it moves parts and vias but fails to move the bend points:

![f](https://user-images.githubusercontent.com/5651184/143328887-843e874f-5925-45e5-88f3-025526c1ce6a.gif)

this is a bit of a showstopper when it comes to optimizing pcb's for size.

**Build:**

Version 0.9.8 
(bCD-92-0-b3d4fefa 2021-08-03) 64 [Qt 5.15.2]

**Operating System:**
Windows 10

**Comment by failiz** [comment] 2021-11-25 01:34
Duplicate of #3609

**Closed** 2021-11-25 09:18 UTC
