### ISSUE TITLE
deal with em and ex units

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2217] opened 2014-08-25 22:43 UTC
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 22, 2012 12:38:05_

"As in CSS, the em and ex unit identifiers are relative to the current font's font-size and x-height, respectively."

Haven't seen these come up in practice. As I understand it, these would only appear as internal units.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2217_

**Comment by KjellMorgenstern** [comment] 2020-04-15 10:30
Closing, it is is not even clear if the issue is about styles in svg, or in the UI.

**Closed by KjellMorgenstern** 2020-04-15 10:30 UTC
Labels: Priority-Low, enhancement, imported
