### ISSUE TITLE
PCB Bottom layer font rendering problem

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2917] opened 2014-08-26 12:02 UTC
_From [colorado...@gmail.com](https://code.google.com/u/109160501376472476728/) on February 09, 2014 18:41:10_

What steps will reproduce the problem? 1. File|New
2. Select PCB View
3. Drag the "logo" part onto the board
4. Change the text to "®©®" (registered, copyright, registered symbols)
5. Note that the text is rendered properly.
6. Change logo's "pcb layer" setting to "silkscreen bottom" or "copper bottom"
7. Note that the text is rendered improperly. Attach your sketch file and/or custom part files to the bug report. Image (PNG) showing problem attached. What is the expected output? What do you see instead? I expect to see an reversed image of the text "®©®", instead I see  "®A©A" with the characters rendered reversed. What version of Fritzing are you using? On what operating system? Fritzing 0.8.7b on Linux Fedora 19 Please provide any additional information below. LANG=en_US.utf8

Surprisingly, the text is rendered properly when exporting the PCB as SVG.

This worked fine in 0.7.12b

**Attachment:** [bad_fritzing_text.png](http://code.google.com/p/fritzing/issues/detail?id=2919)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2919_

**Comment by failiz** [comment] 2021-01-17 12:17
I cannot reproduce this in 0.9.4 Windows.

**Comment by KjellMorgenstern** [comment] 2021-08-16 14:48
Neither on Linux, and there are no other reports for 7 years. Closing.

**Closed by KjellMorgenstern** 2021-08-16 14:48 UTC
Labels: bug, imported, PCB View
