### ISSUE TITLE
Sometimes sending a part to front or to back changes other items' layer orientation

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2949] opened 2014-08-26 12:03 UTC
_From [Per...@gmail.com](https://code.google.com/u/101092636704265404242/) on April 27, 2014 14:19:49_

What steps will reproduce the problem? 1. Create a sketch with several parts and connecting lines on a prototype board.
2. Copy that board and paste it next to the original.
3. Select something on the copy and tell it to move to front or back. Attach your sketch file and/or custom part files to the bug report. Problem difficult to see in a static file, as it's how the app responds to telling a part to move forwards or backwards in layers. What is the expected output? What do you see instead? I expect the part I told to go backwards or forwards in layers to do just that. Sometimes they move up or down in the layer. Sometimes they don't. Often many other parts move up and down in the layers as a result of trying to move a different part up or down. Very frustrating. What version of Fritzing are you using? On what operating system? version 0.8.7 on a Mac Laptop using OSX 10.6.8 Please provide any additional information below. I find the whole layers control to be very frustrating in this version. Not only do things randomly rearrange themselves in the layers, parts occasionally disappear behind the prototype board. I feel the app needs a layers control much more like Photoshop, where the user has control over exactly where parts are in each layer and what layer is above what. For instance, there are times I really need a part to be above a connector line, yet that's completely impossible currently. I'd also love a layers menu where I could simply drag each part to where I want it in the layers (like Photoshop). I waste huge amounts of time and frustration trying to get a part to be above and below where it needs to be, only to have it move higher or lower when I change something else.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2951_

**Comment by failiz** [comment] 2021-03-21 14:01
Send backwards/bring forward do not seems to work well (maybe there are so many layers). However, the send to back/bring to front works well. I did not experience any other component moving when raising/lowering a component.
Remove imported label.

**Comment by failiz** [comment] 2021-10-03 21:12
Duplicate of #3627 and #3632

**Comment by KjellMorgenstern** [comment] 2021-10-30 10:29
Lets see how the improvement works before planning or even implementing further optimizations. Closing for now.

**Closed by KjellMorgenstern** 2021-10-30 10:29 UTC
Labels: bug, Priority-High
