### ISSUE TITLE
stripboard very slow over a certain number of holes

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2382] opened 2014-08-26 07:32 UTC
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 16, 2013 13:35:16_

any way to optimize this? Maybe it applies to the breadboard as well?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2383_

**Comment by tolland** [comment] 2015-05-19 08:37
resizing the stripboard also seems to hang fritzing 0.92 on linux. It sits at 100% CPU for a while, and then when it returns, the UI has gone screwy and the main editing area is crashed.

**Comment by failiz** [comment] 2021-03-24 20:14
duplicate of #2998

**Closed** 2021-03-25 21:38 UTC
Labels: Priority-Low, enhancement, imported
