### ISSUE TITLE
PCB size always too small by 1 mm

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2101] opened 2014-08-25 22:38 UTC
_From [jerome.b...@gmail.com](https://code.google.com/u/109375043177863169589/) on July 09, 2012 08:29:27_

Since last revision (0.7.5b), pcbs are rounded to 1 mm (which is nice). However, the rounding seems to be always false by 1 mm. The dashed bounding box actually has the correct size, but the active area inside is 1 mm smaller.

**Attachment:** [bug-size-10mm.png](http://code.google.com/p/fritzing/issues/detail?id=2101)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2101_

**Comment by failiz** [comment] 2021-03-25 22:04
Duplicate of #2993

**Closed** 2021-03-26 14:26 UTC
Labels: bug, imported
