### ISSUE TITLE
Bug when changing perfboard properties (column and row) when there are parts attached. 

### ISSUE THREAD

**Issue by notalentgeek** [fritzing/fritzing-app#3306] opened 2017-01-23 13:52 UTC
Check these photos, [http://imgur.com/a/Wakhz](http://imgur.com/a/Wakhz). I am using Ubuntu MATE 16.04.

**Comment by failiz** [comment] 2021-03-24 20:22
Duplicate of #3414

**Closed** 2021-03-26 13:32 UTC
