### ISSUE TITLE
Extending stripboard

### ISSUE THREAD

**Issue by ennay69** [fritzing/fritzing-app#3162] opened 2015-12-01 21:28 UTC
A)  When stripboard is extended this gives an extension with all holes linked, both horizontally and vertically.
Correcting this manually is a very slow process.

B) Extending a stripboard results in very slow responses (7 seconds on my i5 4 processor m/c) to any action.

**Comment by failiz** [comment] 2021-03-24 20:14
duplicate of #2998

**Closed** 2021-03-26 13:30 UTC
Labels: Breadboard View, Stripboard + Perfboard, enhancement
