### ISSUE TITLE
when a wire is drawn from the breadboard, default to the color ...

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2042] opened 2014-08-25 22:35 UTC
_From [orgfritz...@gmail.com](https://code.google.com/u/115834879217412145280/) on June 18, 2012 05:20:53_

a cable, what is taken from a breadboard connection, should automaticaly have the color of the ratsnest

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2042_

**Comment by failiz** [comment] 2021-03-23 22:57
Duplicate of #1782

**Closed** 2021-03-23 23:44 UTC
Labels: enhancement, imported
