### ISSUE TITLE
grid is not available in PCB view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2821] opened 2014-08-26 11:58 UTC
_From [eero.ha...@gmail.com](https://code.google.com/u/109634745033994792479/) on December 16, 2013 11:51:31_

What steps will reproduce the problem? 1. open Frizing Version 0.8.4 (b8b2c 2013-12-07) [Qt 4.8.5]
2. open old frizing file (made with earlier version.
3. select PCB view  -> Grid is not available 
(background color is same as grid color) Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Frizing Version 0.8.4 (b8b2c 2013-12-07) [Qt 4.8.5] on Linux Please provide any additional information below. Thank You
- Eero -

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2823_

**Comment by failiz** [comment] 2021-03-27 10:04
Duplicate of #3750

**Closed** 2021-03-27 20:02 UTC
Labels: Priority-Low, enhancement, imported
