### ISSUE TITLE
Different bendpoint drag behaviour across views

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1818] opened 2014-08-25 22:25 UTC
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on February 02, 2012 13:05:37_

Currently, when a wire or wire segment is selected in a group with other things, only in PCB view will they be dragged along.
In bb and schem view this is not the case, which sometimes makes moving an already laid out group very cumbersome.

Is there a reason for this distinction? Otherwise I would say let's make this the same for all as in pcb view.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1818_

**Comment by failiz** [comment] 2021-11-03 23:10
Duplicate of #3609

**Comment by KjellMorgenstern** [comment] 2023-02-17 16:54
Closing in favor of #3609

**Closed by KjellMorgenstern** 2023-02-17 16:54 UTC
Labels: enhancement, imported, Priority-High, UI
