### ISSUE TITLE
Wrong dimensions on Gerber output file

### ISSUE THREAD

**Issue by Jose60** [fritzing/fritzing-app#3314] opened 2017-02-07 12:49 UTC
I did a PCB with 80X50 mm and the GBL file have x=3108 and y=1936.
Can someone help me? My knowledge is very poor about this.
Thanks in advance.
Jose

**Comment by VeitSanner** [comment] 2017-03-07 08:38
Seems to be a duplicate with #3313.

Can this be removed?

**Comment by failiz** [comment] 2021-11-02 21:30
Duplicate of #3313, which has been closed

**Closed** 2021-11-02 22:46 UTC
